### ISSUE TITLE
[Suggestion] Config to cap the amount of ghouls that can be out on the field.

### ISSUE THREAD

**Issue by Thresh90** [BogRtM/Mortician#1]
Did a multiplayer session not too long ago and having 10 or so ghouls out, due to the stacking VFXand just in general presence, it lagged the game like hell.

I know you are aware of how OP this character is but I think at least capping how many you can have out can for the most part, fix the lagging issue.

**Comment by BogRtM** [comment]
> Did a multiplayer session not too long ago and having 10 or so ghouls out, due to the stacking VFXand just in general presence, it lagged the game like hell.
> 
> I know you are aware of how OP this character is but I think at least capping how many you can have out can for the most part, fix the lagging issue.

Sorry for the late reply; I didn't do much last week, but I will try to get this done next patch.
