### ISSUE TITLE
[Bug] Elite Tombstones do not spawn elite ghouls

### ISSUE THREAD

**Issue by Thresh90** [BogRtM/Mortician#2]
basically as it says, while the tombstone and ghouls you summon are elite, the ones that the tombstone summons are not.

**Comment by BogRtM** [comment]
This should have been fixed with the 0.1.4 patch; are you on that patch and still experiencing this issue?

**Comment by Thresh90** [comment]
Oh this is fixed, i just forgot to update it, my bad !
